### ISSUE TITLE
Footer con organzaciones aliadas y link a colaborar

### ISSUE THREAD

**Issue by paulinabustos** [CodeandoMexico/unhabitat-ciudades-equitativas#21]
Agregar el logo de las organizaciones aliadas al footer de la página.

@miguelsalazar: Estoy pensando en estos logos/secciones: 

![image](https://cloud.githubusercontent.com/assets/6033705/5824586/6806a94e-a09a-11e4-8c52-5e416b62b173.png)

**Comment by miguelsalazar** [comment]
Done.
