### ISSUE TITLE
Icono de esquina izquierda

### ISSUE THREAD

**Issue by paulinabustos** [CodeandoMexico/unhabitat-ciudades-equitativas#22]
@miguelsalazar @jimenezjrs @sofiamoya ¿Cómo ven si cambiamos el logo de la esquina izquierda a este?: 

![image](https://cloud.githubusercontent.com/assets/6033705/5881924/cdbcafe8-a2f9-11e4-9de4-09b1f7e48bff.png)

Para que no se repita el logo con el footer, ¿o cómo quedaría mejor?

**Comment by miguelsalazar** [comment]
Pau, no se ve el logo.

**Comment by paulinabustos** [comment]
Listo, es el que esta en la portada del libro.

**Comment by poguez** [comment]
Está muy pesado para lo pequeño que está el espacio :grin:  ¿no? algo más sencillo.

**Comment by miguelsalazar** [comment]
Fixed.
