### ISSUE TITLE
Cambiar logo de Github por un Colabora y un ícono pequeño 

### ISSUE THREAD

**Issue by paulinabustos** [CodeandoMexico/unhabitat-ciudades-equitativas#28]
En el footer el logo de Githu debería ir acompañado de un Colabora con nosotros y luego el logo del octocat. Mockup:
![image](https://cloud.githubusercontent.com/assets/6033705/6074903/4cb188d6-ad7d-11e4-85be-84d2eed8eaa6.png)

**Comment by miguelsalazar** [comment]
Fixed.
