### ISSUE TITLE
La pantalla 1024x768 no se visualiza bien.

### ISSUE THREAD

**Issue by poguez** [CodeandoMexico/unhabitat-ciudades-equitativas#29]
![screen shot 2015-02-05 at 11 53 06 pm](https://cloud.githubusercontent.com/assets/732015/6075138/45cabe9c-ad92-11e4-8997-111fa6f41ebf.png)

**Comment by paulinabustos** [comment]
@poguez Creo que este issue ya quedó, ¿qué opinas?

**Comment by poguez** [comment]
Sí, se ve bien. :smile_cat:
