### ISSUE TITLE
Generar estadísticas rápidas

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/unhabitat-ciudades-equitativas#36]
* Las 5 ciudades más desiguales
* Las 5 ciudades menos desiguales
* Los 5 países más desiguales
* Los 5 países menos desiguales

**Comment by ricalanis** [comment]
Acá las stats

https://drive.google.com/open?id=0B7Tb1TEriMqTLXRINUpFZ1luMFk&authuser=0

**Comment by miguelsalazar** [comment]
Done. Will close issue.
