### ISSUE TITLE
Determinar las ciudades más importantes de cada país

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/unhabitat-ciudades-equitativas#38]
Determinar las ciudades más importantes de cada país. A criterio, pero recomiendo ser consistente (por ejemplo: capitales + ciudades de 1M de personas). Estas ciudades son las que desplegaran el nombre en el mapa.
Ciudado con países donde haya muchas ciudades.

**Comment by ricalanis** [comment]
Mike, en que formato te entrego esta información o dónde la ponemos?

**Comment by miguelsalazar** [comment]
top.csv
pais,ciudad

**Comment by miguelsalazar** [comment]
List of most important cities was produced. Will close issue.
