### ISSUE TITLE
Al cambiar la opción de Decil la gráfica no se actualiza

### ISSUE THREAD

**Issue by paulinabustos** [CodeandoMexico/unhabitat-ciudades-equitativas#45]
@ricalanis En la gráfica de Consumo por deciles, al cambiar la opción del decil no se actualiza la gráfica. 

¿será porque no hay datos?

**Comment by ricalanis** [comment]
Parece que es el código de la limpieza del div que estaba usando, que ahora está roto. Voy a rebotarlo con @miguelsalazar

**Comment by paulinabustos** [comment]
Ok, hay que revisarlo.
